### PR TITLE
ENH: implement Arduino-based I2C interface to IrradDAQBoard

### PR DESCRIPTION
**Pull request by bedakno**
Added scripts to _irrad_control/devices/arduino_ and created said folder. The folder contains scripts which are implemented into the _TCA9555.py_ script so that it doesn't communicate via i2c but serial now. The direct link to the controller TCA9555 is handled by an arduino which is to be programmed by the included _.ino_ script.
The usability of the _IrradDAQBoard.py_ script didn't change as only the communication format was altered.

### CODE REVIEW

**Review by leloup314 — CHANGES_REQUESTED** [review]
The class names are mixed up: `ArduinoToI2C` is the general class, so should be named `ArduinoSerial` and vice versa

**Comment by leloup314** [comment]
@bedakno could you do me a favor and check if the soft / firmware run without resetting the in/output buffers? I think there should be no need to do so. That may help with the delays

**Comment by bedakno** [comment]
> The class names are mixed up: `ArduinoToI2C` is the general class, so should be named `ArduinoSerial` and vice versa

**Comment by bedakno** [comment]
I'm confused ^^. Yeah, sure. I'll fix that tomorrow.

**Comment by bedakno** [comment]
Improvements added :)

**Comment by leloup314** [comment]
Looks good to me now, did you test the latest changes with the board?

**Comment by leloup314** [comment]
I think a good test is to cycle the ntc channels for a bit (with a timeout of 0.2 seconds)

**Comment by bedakno** [comment]
Cycling works too.

**Comment by bedakno** [comment]
I didn't remove the delays. That didn't work. But I did remove the buffer resets.

**Comment by leloup314** [comment]
Did you also remove the buffer reset on the Arduino side?

**Review by leloup314 — APPROVED** [review]
Looks good

**Comment by bedakno** [comment]
> Did you also remove the buffer reset on the Arduino side?

No. I actually didn't try without, but with logic I use to read the serial port, I'd rather just reset it afterwards. That shouldn't take too long especially when it is empty.

**Comment by bedakno** [comment]
Yey

**Pull request merged**
